{"name": "新增用户", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'json'", "trace": "self = <tc.test_userManage.TestUserManage object at 0x03FAC718>\ninData = '{\"password\":\"\",\"password_confirm\": \"88888888\",\"username\":\"001\"}'\nexp = '{\\'code\\':500,\\'msg\\':\"Key:\\'userAddRequest.password\\'Error:Field validation for \\'password\\' failed on the\\'required\\' tag\"}'\n\n    @allure.title(\"新增用户\")\n    @pytest.mark.parametrize(\"inData,exp\",get_excel_data(\"user\",2,6,7,8))\n    def test_add_user(self,inData,exp):\n        res = UserManage().add_user(self.token,inData)\n        print(inData)\n>       assert self.test.assert_code(res.json()[\"code\"],200)\nE       AttributeError: 'dict' object has no attribute 'json'\n\ntest_userManage.py:19: AttributeError"}, "attachments": [{"name": "log", "source": "e20baf31-e7a4-47c5-8c13-7b3bc2710479-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "inData", "value": "'{\"password\":\"\",\"password_confirm\": \"88888888\",\"username\":\"001\"}'"}, {"name": "exp", "value": "'{'code':500,'msg':\"Key:'userAddRequest.password'Error:Field validation for 'password' failed on the'required' tag\"}'"}], "start": 1604654461419, "stop": 1604654461427, "uuid": "a861a3e1-6ab3-49d8-bba8-db663c796544", "historyId": "f857598b92e6035d3ec25e0a063fad38", "testCaseId": "f56f10c6b6679a14e1ccd1e8f399d334", "fullName": "test_userManage.TestUserManage#test_add_user", "labels": [{"name": "suite", "value": "test_userManage"}, {"name": "subSuite", "value": "TestUserManage"}, {"name": "host", "value": "dadaxPC008"}, {"name": "thread", "value": "15092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_userManage"}]}